Survey Assist Updates
ONS-Innovation/innovation-ai-assist pull request #4
Opened 2024-12-20 14:55 UTC by gibbardsteve

- Rework to use a json structure for survey definition 
(note: flexibility needs to be added to /save_response to make this truly defined by json)
- Interact with Survey Assist API (routes, /survey_assist /survey_assist_results /save_results
- Introduce Classification to show output of interactions with Survey Assist
- Add test admin screen

2024-12-24 14:32 UTC, delterr requested changes
Good first POC - Minor nitpicks with code quality and refactoring.

2024-12-24 14:32 UTC, delterr commented on ai_assist_builder/utils/results_utils.py
> +        for question in enumerate(questions):
Nested for loop - break down into helper function

2024-12-24 14:32 UTC, delterr commented on ai_assist_builder/utils/results_utils.py
> +                    for candidate in candidates:
Break down into helper function

2025-01-06 13:19 UTC, gibbardsteve commented on ai_assist_builder/__init__.py
> +        print(f"Request form: {request}")
The route renders the login template, but yep the POST isn't needed that code is left over from debug. I have removed it.

2025-01-06 13:20 UTC, gibbardsteve commented on ai_assist_builder/__init__.py
> +    if request.method == "POST":
Not necessary, hangover from some faffing of mine. I have removed it.

2025-01-06 13:20 UTC, gibbardsteve commented on ai_assist_builder/__init__.py
> +    except Exception as e:
I have been more specific in the except cases

2025-01-06 13:22 UTC, gibbardsteve commented on ai_assist_builder/__init__.py
> +                            ] += f". Organisation is NOT {response['value']}"
Agreed - I will refactor this code as part of iterating the code so it won't be changed for this review (there is a TODO comment above functions that I have targeted for refactor)

2025-01-06 13:24 UTC, gibbardsteve commented on ai_assist_builder/__init__.py
> +    print("====================")
I have a general refactor comment for this. I'll make it simpler in the next iteration.

2025-01-06 13:27 UTC, gibbardsteve commented on ai_assist_builder/__init__.py
> +        return redirect(url_for("error_page"))
Made it more specific

2025-01-06 13:29 UTC, gibbardsteve commented on ai_assist_builder/utils/results_utils.py
> +        for question in enumerate(questions):
Yep, there is a refactor comment above this function - I will simplify in the future.

2025-01-06 13:29 UTC, gibbardsteve commented on ai_assist_builder/utils/results_utils.py
> +                    for candidate in candidates:
For a future refinement

2025-01-07 12:01 UTC, delterr approved these changes
Could do with a bit of refactoring in the future but looks good enough as of now to get merged

2025-01-13 10:05 UTC, merged